name: Continuous Integration and Deployment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_API_URL: https://backend-nz4jxdcc7a-as.a.run.app

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run test:ci

      - name: Build Next.js App
        run: npm run build
        
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: code checkout
        uses: actions/checkout@v2

      - name: install the cloud cli
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          export_default_credentials: true
      
      - name: build and push docker image
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
          NEXT_PUBLIC_API_URL: https://backend-nz4jxdcc7a-as.a.run.app
        run: |
          gcloud auth configure-docker asia-southeast1-docker.pkg.dev
          docker build --build-arg NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL} -t asia-southeast1-docker.pkg.dev/myworkshop-416015/workshop-repo/frontend:latest .
          docker push asia-southeast1-docker.pkg.dev/myworkshop-416015/workshop-repo/frontend:latest
      # - name: Deploy to Cloud Run
      #   env:
      #     SERVICE_NAME: frontend	
      #     IMAGE_URL: asia-southeast1-docker.pkg.dev/myworkshop-416015/workshop-repo/frontend:latest
      #     REGION: asia-southeast1
      #   run: |
      #     gcloud run deploy $SERVICE_NAME \
      #       --image $IMAGE_URL \
      #       --region $REGION \
      #       --platform managed \
      #       --allow-unauthenticated